### ISSUE TITLE
Still supporting?

### ISSUE THREAD

**Issue by Makazzz** [JarlPenguin/DiscordPortable#1]
Are you still supporting the Discord in PAF ? Because I found a way to make it more portable without directory move and I can test it later. I just need to make it to a test just to be sure.

PS: You can see my work about PortableApps in my GitHub profile if you want.

**Comment by JarlPenguin** [comment]
This project isn't really dead, but I'm not working actively on it. You can always open a PR with your contributions if you'd like.
